global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'slack-notifications'
  repeat_interval: 1h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/TOKEN'
        channel: '#alerts'
        send_resolved: true
